from pathlib import Path
from typing import Any, Mapping

class Post:
    metadata: dict[str, Any]
    content: str
    handler: Any

    def __init__(
        self,
        content: str = ...,
        handler: Any = ...,
        **metadata: Any,
    ) -> None: ...

    def __getitem__(self, name: str) -> Any: ...
    def __setitem__(self, name: str, value: Any) -> None: ...
    def __delitem__(self, name: str) -> None: ...
    def get(self, key: str, default: Any = ...) -> Any: ...
    def keys(self) -> Any: ...
    def values(self) -> Any: ...
    def items(self) -> Any: ...

class YAMLHandler:
    Loader: Any
    Dumper: Any

    def __init__(self, **kwargs: Any) -> None: ...

def load(fd: str | Path | Any, encoding: str | None = ..., handler: Any = ..., **defaults: Any) -> Post: ...
def loads(text: str, encoding: str | None = ..., handler: Any = ..., **defaults: Any) -> Post: ...
def dump(post: Post, fd: str | Path | Any, encoding: str | None = ..., handler: Any = ...) -> None: ...
def dumps(post: Post | str, handler: Any = ..., **metadata: Any) -> str: ...
